"""Test data for AfvalWijzer tests.

This module contains test addresses for all supported providers.
Each address includes provider, postal_code, street_number, and optionally suffix.
"""

# fmt: off
TEST_ADDRESSES = [
    #{"provider": "acv", "postal_code": "6713CG", "street_number": "11"},
    #{"provider": "afval3xbeter", "postal_code": "4874AA", "street_number": "42"},
    #{"provider": "afvalstoffendienst", "postal_code": "5222AA", "street_number": "5"},
    #{"provider": "afvalstoffendienstkalender", "postal_code": "5237BE", "street_number": "2"},
    #{"provider": "afvalstoffendienstkalender", "postal_code": "5473JD", "street_number": "3"},
    #{"provider": "almere", "postal_code": "1311HG", "street_number": "20"},
    #{"provider": "alphenaandenrijn", "postal_code": "2408CV", "street_number": "5"},
    #{"provider": "amsterdam", "postal_code": "1066KC", "street_number": "18"},
    #{"provider": "areareiniging", "postal_code": "7812PC", "street_number": "107"},
    #{"provider": "areareiniging", "postal_code": "7848CT", "street_number": "8"},
    #{"provider": "assen", "postal_code": "9403XT", "street_number": "19"},
    #{"provider": "avalex", "postal_code": "2611XG", "street_number": "87"},
    #{"provider": "avri", "postal_code": "4011EJ", "street_number": "33"},
    #{"provider": "avri", "postal_code": "4105HB", "street_number": "35"},
    #{"provider": "avri", "postal_code": "4191LE", "street_number": "24"},
    #{"provider": "bar", "postal_code": "2992VE", "street_number": "29"},
    #{"provider": "bar", "postal_code": "3161XB", "street_number": "13", "suffix": "b"},
    #{"provider": "blink", "postal_code": "5721HP", "street_number": "28"},
    #{"provider": "blink", "postal_code": "5741MD", "street_number": "24"},
    #{"provider": "circulus", "postal_code": "6961PG", "street_number": "60"},
    #{"provider": "circulus", "postal_code": "7221AA", "street_number": "3"},
    #{"provider": "circulus", "postal_code": "7327BV", "street_number": "508"},
    #{"provider": "circulus", "postal_code": "7421AC", "street_number": "1"},
    #{"provider": "cranendonck", "postal_code": "6021XV", "street_number": "25"},
    #{"provider": "cyclus", "postal_code": "2411JS", "street_number": "51"},
    #{"provider": "cyclus", "postal_code": "2805GG", "street_number": "25"},
    #{"provider": "dar", "postal_code": "6532AJ", "street_number": "1"},
    #{"provider": "dar", "postal_code": "6562BH", "street_number": "27"},
    #{"provider": "dar", "postal_code": "6644BD", "street_number": "8"},
    #{"provider": "dar", "postal_code": "6665CN", "street_number": "1"},
    #{"provider": "deafvalapp", "postal_code": "5427JR", "street_number": "18"},
    #{"provider": "deafvalapp", "postal_code": "5708TE", "street_number": "2"},
    #{"provider": "defryskemarren", "postal_code": "8501BR", "street_number": "21"},
    #{"provider": "denhaag", "postal_code": "2564EX", "street_number": "75"},
    #{"provider": "gad", "postal_code": "1214HA", "street_number": "156"},
    #{"provider": "gad", "postal_code": "1262BC", "street_number": "15"},
    #{"provider": "geertruidenberg", "postal_code": "4941GZ", "street_number": "283"},
    #{"provider": "groningen", "postal_code": "9725KL", "street_number": "5"},
    #{"provider": "hellendoorn", "postal_code": "7447BA", "street_number": "11"},
    #{"provider": "hvc", "postal_code": "1822AL", "street_number": "198"},
    #{"provider": "hvc", "postal_code": "1943BG", "street_number": "3"},
    #{"provider": "hvc", "postal_code": "2951VS", "street_number": "160"},
    #{"provider": "irado", "postal_code": "2903LS", "street_number": "16"},
    #{"provider": "irado", "postal_code": "3114VC", "street_number": "23"},
    #{"provider": "lingewaard", "postal_code": "6851JW", "street_number": "15"},
    #{"provider": "maassluis", "postal_code": "3146BL", "street_number": "22"},
    #{"provider": "meerlanden", "postal_code": "1432KC", "street_number": "277"},
    #{"provider": "meerlanden", "postal_code": "2121CN", "street_number": "22"},
    #{"provider": "meerlanden", "postal_code": "2162JP", "street_number": "2"},
    #{"provider": "middelburg-vlissingen", "postal_code": "4335SW", "street_number": "36"},
    #{"provider": "middelburg-vlissingen", "postal_code": "4388KD", "street_number": "198"},
    #{"provider": "mijnafvalwijzer", "postal_code": "1187HD", "street_number": "10"},
    #{"provider": "mijnafvalwijzer", "postal_code": "3192NC", "street_number": "86"},
    #{"provider": "mijnafvalwijzer", "postal_code": "3601AC", "street_number": "10"},
    #{"provider": "mijnafvalwijzer", "postal_code": "3772WN", "street_number": "16"},
    #{"provider": "mijnafvalwijzer", "postal_code": "3941RK", "street_number": "50", "suffix": "B"},
    #{"provider": "mijnafvalwijzer", "postal_code": "4254CJ", "street_number": "4"},
    #{"provider": "mijnafvalwijzer", "postal_code": "4814HL", "street_number": "33"},
    #{"provider": "mijnafvalwijzer", "postal_code": "4855BD", "street_number": "2"},
    #{"provider": "mijnafvalwijzer", "postal_code": "5111EB", "street_number": "30", "suffix": "a"},
    #{"provider": "mijnafvalwijzer", "postal_code": "5146EG", "street_number": "1"},
    #{"provider": "mijnafvalwijzer", "postal_code": "5282SN", "street_number": "7"},
    #{"provider": "mijnafvalwijzer", "postal_code": "5531DH", "street_number": "37"},
    #{"provider": "mijnafvalwijzer", "postal_code": "5563CM", "street_number": "22"},
    #{"provider": "mijnafvalwijzer", "postal_code": "5685AB", "street_number": "57"},
    #{"provider": "mijnafvalwijzer", "postal_code": "5954CM", "street_number": "14"},
    #{"provider": "mijnafvalwijzer", "postal_code": "7944AB", "street_number": "1"},
    #{"provider": "mijnafvalwijzer", "postal_code": "9511RB", "street_number": "3"},
    #{"provider": "mijnafvalwijzer", "postal_code": "9521HN", "street_number": "80"},
    #{"provider": "mijnafvalzaken", "postal_code": "1861KJ", "street_number": "28"},
    #{"provider": "mijnafvalzaken", "postal_code": "1901XG", "street_number": "7"},
    #{"provider": "montferland", "postal_code": "7041EJ", "street_number": "13"},
    #{"provider": "montfoort", "postal_code": "3461CV", "street_number": "10"},
    #{"provider": "nijkerk", "postal_code": "3861XJ", "street_number": "1"},
    #{"provider": "offalkalinder", "postal_code": "9853PR", "street_number": "12"},
    #{"provider": "omrin", "postal_code": "3844JP", "street_number": "4"},
    #{"provider": "omrin", "postal_code": "8085RT", "street_number": "11"},
    #{"provider": "omrin", "postal_code": "9164KD", "street_number": "6"},
    #{"provider": "omrin", "postal_code": "9285ML", "street_number": "17"},
    #{"provider": "omrin", "postal_code": "9991AB", "street_number": "2"},
    #{"provider": "oudeijsselstreek", "postal_code": "7081GD", "street_number": "79"},
    #{"provider": "peelenmaas", "postal_code": "5991GR", "street_number": "32"},
    #{"provider": "prezero", "postal_code": "6822NG", "street_number": "1"},
    #{"provider": "purmerend", "postal_code": "1462XP", "street_number": "11"},
    #{"provider": "rad", "postal_code": "3252BV", "street_number": "17"},
    #{"provider": "rd4", "postal_code": "6174RL", "street_number": "2"},
    #{"provider": "rd4", "postal_code": "6301ET", "street_number": "6"},
    #{"provider": "rd4", "postal_code": "6441AD", "street_number": "11"},
    #{"provider": "reinis", "postal_code": "3209BS", "street_number": "14"},
    #{"provider": "rmn", "postal_code": "3402TA", "street_number": "1"},
    #{"provider": "rmn", "postal_code": "3701XK", "street_number": "24"},
    #{"provider": "rmn", "postal_code": "3741CP", "street_number": "1"},
    #{"provider": "rmn", "postal_code": "3981CR", "street_number": "17"},
    #{"provider": "rova", "postal_code": "3752CR", "street_number": "16"},
    #{"provider": "rova", "postal_code": "3818NL", "street_number": "58"},
    #{"provider": "rova", "postal_code": "7122VW", "street_number": "34"},
    #{"provider": "rova", "postal_code": "7671BL", "street_number": "2"},
    #{"provider": "rwm", "postal_code": "6105CL", "street_number": "50"},
    #{"provider": "rwm", "postal_code": "6191DZ", "street_number": "4"},
    #{"provider": "saver", "postal_code": "4624HD", "street_number": "29"},
    #{"provider": "saver", "postal_code": "4708LS", "street_number": "10"},
    #{"provider": "schouwen-duiveland", "postal_code": "4301SH", "street_number": "2"},
    #{"provider": "sliedrecht", "postal_code": "3362ND", "street_number": "52"},
    #{"provider": "spaarnelanden", "postal_code": "2025AE", "street_number": "148"},
    #{"provider": "straatbeeld", "postal_code": "4921AH", "street_number": "8"},
    #{"provider": "sudwestfryslan", "postal_code": "8604ED", "street_number": "1"},
    #{"provider": "tilburg", "postal_code": "5038EC", "street_number": "37"},
    #{"provider": "twentemilieu", "postal_code": "7271JG", "street_number": "8"},
    #{"provider": "twentemilieu", "postal_code": "7524AR", "street_number": "3"},
    #{"provider": "twentemilieu", "postal_code": "7609NA", "street_number": "12"},
    #{"provider": "twentemilieu", "postal_code": "7625NJ", "street_number": "12"},
    #{"provider": "uithoorn", "postal_code": "1422KL", "street_number": "24"},
    #{"provider": "venlo", "postal_code": "5922TS", "street_number": "1"},
    #{"provider": "venray", "postal_code": "5802AC", "street_number": "12"},
    #{"provider": "voorschoten", "postal_code": "2251JA", "street_number": "10"},
    #{"provider": "waalre", "postal_code": "5583AS", "street_number": "15"},
    #{"provider": "waardlanden", "postal_code": "4143GD", "street_number": "46"},
    #{"provider": "woerden", "postal_code": "3446GL", "street_number": "16"},
    #{"provider": "ximmio", "postal_code": "2162JP", "street_number": "2"},
    #{"provider": "zrd", "postal_code": "4561MT", "street_number": "3"},
]
# fmt: on
