name: ðŸš¨ Report an issue
description: Report an issue or unexpected behavior with the Afvalwijzer integration.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Sorry to hear you're experiencing an issue! ðŸ›
        Before submitting, please quickly search the [existing issues](../issues) to see if this has already been reported.

  - type: dropdown
    id: language
    attributes:
      label: Language / Voertaal
      description: |
        > [!TIP]
        > *ðŸ‡¬ðŸ‡§ Unable to communicate in Dutch? Welcome anyway! Feel free to use English.*
        > *ðŸ‡³ðŸ‡± Voel je vooral vrij om in het Nederlands te communiceren, ondanks dat het project Engelstalig is.*
      options:
        - 'ðŸ‡³ðŸ‡± Nederlandstalig'
        - 'ðŸ‡¬ðŸ‡§ English'
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: The Problem
      description: >-
        Tell us what you were trying to do and what actually happened.
      placeholder: "When I do [...], the integration does [...] instead of [...]"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: What exact steps do we need to take to replicate the issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Notice the error...
    validations:
      required: true

  - type: input
    id: postal_code
    validations:
      required: true
    attributes:
      label: Postal Code (Area)
      description: Please share the valid postal code you are using for testing so we can replicate the API call.
      placeholder: "e.g., 1234 AB"

  - type: input
    id: version_afvalwijzer
    validations:
      required: true
    attributes:
      label: Afvalwijzer Integration Version
      description: Which version of this integration are you running? (Check HACS or the Integration page).
      placeholder: "e.g., v202X.X.X"

  - type: input
    id: version_hass
    validations:
      required: true
    attributes:
      label: Home Assistant Core Version
      description: Which version of Home Assistant Core are you running? (Check Settings -> System -> About).
      placeholder: "e.g., 202X.X.X"

  - type: textarea
    id: logs
    attributes:
      label: Home Assistant Logs / Error Messages
      description: |
        Please provide the relevant errors or stack traces from your Home Assistant logs (Settings -> System -> Logs). 
        *Tip: It helps immensely if you enable debug logging for this integration first.*
      render: shell
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Information
      description: >-
        Any other context about the problem? You can also attach screenshots or screen recordings by dragging and dropping them into this box.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues to ensure this bug hasn't already been reported.
          required: true
        - label: I have updated both Home Assistant and the Afvalwijzer integration to the latest versions, and the issue still persists.
          required: true
