#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

bash scripts/test > /dev/null
python3 -m pytest \
    -qq \
    --timeout=9 \
    --durations=10 \
    -n auto \
    --cov custom_components.afvalwijzer \
    -o console_output_style=count \
    -p no:sugar \
    custom_components/afvalwijzer/tests
