#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config if not present
if [[ ! -f "${PWD}/config/configuration.yaml" ]]; then
    hass --config "${PWD}/config" --script ensure_config
fi
if ! grep -R "^logger:" config/configuration.yaml >> /dev/null;then
echo "
logger:
    default: info
    logs:
        custom_components.afvalwijzer: debug" >> config/configuration.yaml
fi
if ! grep -R "^isal:" config/configuration.yaml >> /dev/null;then
echo "
isal:" >> config/configuration.yaml
fi
if ! grep -R "debugpy:" config/configuration.yaml >> /dev/null;then
echo "
# Uncomment the line below if you want to use debugger
# debugpy:
" >> config/configuration.yaml
fi


# Set the path to custom_components
## This let's us have the structure we want <root>/custom_components/ake_dev
## while at the same time have Home Assistant configuration inside <root>/config
## without resulting to symlinks.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Start Home Assistant
hass --config "${PWD}/config" --debug
